### ISSUE TITLE
[develop_linux] - Invoking java -jar Roundkeeper.jar fails with exception

### ISSUE THREAD

**Issue by JDKoder** [JDKoder/RoundKeeper#16]
The following invocation and error pair are present. 

`~/git_repos/RoundKeeper/target$ java -jar RoundKeeper.jar 
Exception in thread "main" java.lang.ClassNotFoundException: com.warriorwebpros.Main
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:495)
        at java.base/java.lang.Class.forName(Class.java:474)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
`

Should be able to invoke this target and have the application begin running.

**Comment by JDKoder** [comment]
Now able to execute program after running `ant build` from root project directory followed by `java -jar target/RoundKeeper-1.0.0.1.jar`
